// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Stock.Shared.Models;
//
//    var optionsScreeningResponse = OptionsScreeningResponse.FromJson(jsonString);

namespace Stock.Shared.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class OptionsScreeningResponse
    {
        [JsonProperty("status")]
        public ResponseStatus Status { get; set; }

        [JsonProperty("results")]
        public List<OptionsScreeningResult> Results { get; set; }
    }

    public class OptionsScreeningResult
    {
        [JsonProperty("underlyingSymbol")]
        public string UnderlyingSymbol { get; set; }

        [JsonProperty("instrumentType")]
        public string InstrumentType { get; set; }

        [JsonProperty("exchange")]
        public string Exchange { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("strike")]
        public decimal Strike { get; set; }

        [JsonProperty("expirationDate")]
        public DateTimeOffset ExpirationDate { get; set; }
        
        public string ExpirationDateFormatted => ExpirationDate.ToString("yyyyMMdd");

        [JsonProperty("lastPrice")]
        public decimal LastPrice { get; set; }

        [JsonProperty("optionPrice")]
        public decimal OptionPrice { get; set; }

        [JsonProperty("optionNetChange")]
        public decimal OptionNetChange { get; set; }

        [JsonProperty("tradeTime")]
        public DateTimeOffset TradeTime { get; set; }
        
        public string TradeTimeFormatted => TradeTime.ToString("yyyy-MM-dd HH:mm:ss");

        [JsonProperty("delta")]
        public decimal Delta { get; set; }

        [JsonProperty("volume")]
        public double Volume { get; set; }

        [JsonProperty("openInterest")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long OpenInterest { get; set; }

        [JsonProperty("volumeOpenInterestRatio")]
        public decimal VolumeOpenInterestRatio { get; set; }
        
        public double OpenInterestPercentageChange { get; set; }
    }

    public partial class OptionsScreeningResponse
    {
        public static OptionsScreeningResponse FromJson(string json) => JsonConvert.DeserializeObject<OptionsScreeningResponse>(json, Stock.Shared.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this OptionsScreeningResponse self) => JsonConvert.SerializeObject(self, Stock.Shared.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
